project:
  title: "Modelling Infectious Diseases"
  output-dir: student_materials
  type: website
  render:
    - index.qmd
    - session1_intro_to_mathematical_modelling/session1_intro_to_mathematical_modelling.qmd
    - session2_differential_equations_in_r/session2_differential_equations_in_r.qmd
    - session3_writing_a_model_to_suit_the_infectious_agent/session3_writing_a_model_to_suit_the_infectious_agent.qmd
    - session4_covid_thailand_seir_model/session4_covid_thailand_seir_model.qmd
    - session5_fitting_models_in_r/session5_fitting_models_in_r.qmd
    - session7_vector_borne_modelling/session7_vector_borne_modelling.qmd
    - session8_vector_borne_modelling_in_r/session8_vector_borne_modelling_in_r.qmd
    - session9_modelling_interventions_in_r/session9_modelling_interventions_in_r.qmd
  resources:
    - ./first_wave_TH.csv
    - ./session1_introduction_beans.R
    - ./session1_introduction_beans_complete.R
    - ./session2_differential_equations_practical.R
    - ./session2_differential_equations_part1.R
    - ./session2_differential_equations_core.R
    - ./shiny_app_SEIRS_variations.R
    - ./session4_covid_model_initial.R
    - ./session4_covid_model_complete.R
    - ./session5_fitting_models_least_squares.R
    - ./session5_fitting_models_maximum_likelihood.R
    - ./session5_fitting_models_complete.R
    - ./session8_vector_model.R
    - ./session8_vector_model_part1.R
    - ./session8_vector_model_part2.R
    - ./session8_vector_model_part3.R
    - ./session9_interventions_initial_model.R
    - ./session9_interventions_calibrated_model.R
toc: true
format:
  training-html:
    embed-resources: true

execute:
  freeze: auto

website:
  sidebar:
    title: "Modelling Infectious Diseases"
    style: floating
    search: true
    logo: logo.png
    border: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Session 1: Introduction to mathematical modelling"
        href: session1_intro_to_mathematical_modelling/session1_intro_to_mathematical_modelling.qmd
      - text: "Session 2: Differential equations in R"
        href: session2_differential_equations_in_r/session2_differential_equations_in_r.qmd
      - text: "Session 3: Designing a model to suit the pathogen"
        href: session3_writing_a_model_to_suit_the_infectious_agent/session3_writing_a_model_to_suit_the_infectious_agent.qmd
      - text: "Session 4: Modelling an outbreak—COVID-19 in Thailand"
        href: session4_covid_thailand_seir_model/session4_covid_thailand_seir_model.qmd
      - text: "Session 5: Fitting models in R"
        href: session5_fitting_models_in_r/session5_fitting_models_in_r.qmd
      - text: "Session 7: Vector-borne disease modelling"
        href: session7_vector_borne_modelling/session7_vector_borne_modelling.qmd
      - text: "Session 8: Vector-borne disease models in R"
        href: session8_vector_borne_modelling_in_r/session8_vector_borne_modelling_in_r.qmd
      - text: "Session 9: Modelling interventions in R"
        href: session9_modelling_interventions_in_r/session9_modelling_interventions_in_r.qmd
  page-footer:
    left: |
      For more information or to report issues, please contact <a href='mailto:spectrum-spark@unimelb.edu.au'>the SPARKLE project inbox</a>. <br>
      © 2026 SPARKLE
    right: |
      SPARKLE is funded by the Australian Department of Foreign Affairs and Trade (DFAT)
    background: "#4BA5AB"
    foreground: "#FFFFFF"
