project:
  title: "Modelling Infectious Diseases"
  output-dir: student_files
  type: website
  resources: ['session1_introduction_beans.R', 'session8_vector_model.R']
toc: true
format:
  html:
    css: style.css
    title-block-style: none
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true

  

execute:
  freeze: auto

website:
  sidebar:
    contents:
      - href: session1_intro_to_mathematical_modelling/session1_intro_to_mathematical_modelling.qmd
      - href: session2_differential_equations_in_r/session2_differential_equations_in_r.qmd
      - href: session3_writing_a_model_to_suit_the_infectious_agent/session3_writing_a_model_to_suit_the_infectious_agent.qmd
      - href: session4_covid_thailand_seir_model/session4_covid_thailand_seir_model.qmd
      - href: session5_fitting_models_in_r/session5_fitting_models_in_r.qmd
      - href: session7_vector_borne_modelling/session7_vector_borne_modelling.qmd
      - href: session8_vector_borne_modelling_in_r/session8_vector_borne_modelling_in_r.qmd
      
