project:
  title: "Modelling Infectious Diseases"
  output-dir: student_materials
  type: website
  resources: ['session1_introduction_beans.R', 'session8_vector_model.R', 'shiny_app_SEIRS_variations.R', 'first_wave_TH.csv']
toc: true
format:
  html:
    theme: cosmo
    css: style_training.css
    title-block-style: none
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true

  

execute:
  freeze: auto

website:
  sidebar:
    title: "Modelling Infectious Diseases"
    style: floating
    search: true
    logo: logo.png
    border: true
    contents:
      - href: session1_intro_to_mathematical_modelling/session1_intro_to_mathematical_modelling.qmd
      - href: session2_differential_equations_in_r/session2_differential_equations_in_r.qmd
      - href: session3_writing_a_model_to_suit_the_infectious_agent/session3_writing_a_model_to_suit_the_infectious_agent.qmd
      - href: session4_covid_thailand_seir_model/session4_covid_thailand_seir_model.qmd
      - href: session5_fitting_models_in_r/session5_fitting_models_in_r.qmd
      - href: session7_vector_borne_modelling/session7_vector_borne_modelling.qmd
      - href: session8_vector_borne_modelling_in_r/session8_vector_borne_modelling_in_r.qmd
      - href: session9_modelling_interventions_in_r/session9_modelling_interventions_in_r.qmd
  page-footer:
    left: |
      For more information or to report issues, please contact <a href='mailto:spectrum-spark@unimelb.edu.au'>the consortia project inbox</a>. <br>
      © July 2025 SPARKLE
    right: |
      SPARKLE is funded by the Australian Department of Foreign Affairs and Trade (DFAT)
    background: "#4BA5AB"
    foreground: "#FFFFFF"
      
