on:
  workflow_dispatch:
  push:
    branches:
      - main


name: Copy to training site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /docs
          src_branch: main
          dst_path: /InfectiousDiseasesCourse/
          dst_branch: main
          dst_owner: spectrum-spark
          dst_repo_name: courses